#!/usr/bin/env python3
"""Embed the precomputed data/ JSON into cancer-explorer.html.

Browsers forbid a page opened over file:// from reading sibling local files, so
`fetch("data/*.json")` silently fails when the dashboard is opened with `open
cancer-explorer.html` (no server). Baking the precomputed payload straight into
the HTML removes the local folder to read, so dynamics / priority / pockets and
the full gene picker work on a plain double-click.

`data/` stays the source of truth (served mode + the live API still fetch it);
this script just mirrors it into the self-contained file. It is idempotent and is
also invoked at the end of scripts/precompute.py so the two never drift.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
HTML = ROOT / "cancer-explorer.html"

START = "<!-- PRECOMPUTED:START (generated by scripts/embed_data.py — do not edit by hand) -->"
END = "<!-- PRECOMPUTED:END -->"
# The dashboard's own <script> block (line ~460): a bare opening tag on its own
# line, as opposed to the CDN <script src=...> at the top.
APP_SCRIPT = "\n<script>\n"


def build_payload() -> dict:
    """Collect data/index.json + every data/{GENE}.json into one embeddable object."""
    genes: dict[str, dict] = {}
    for path in sorted(DATA_DIR.glob("*.json")):
        if path.name == "index.json":
            continue
        genes[path.stem.upper()] = json.loads(path.read_text())
    index_path = DATA_DIR / "index.json"
    index = json.loads(index_path.read_text()) if index_path.exists() else {"genes": []}
    return {"index": index, "genes": genes}


def render_block(payload: dict) -> str:
    # Minify, and escape '<' so a stray "</script>" or "<!--" inside the data
    # (e.g. PDB text) can never break out of the <script> tag. JSON.parse decodes
    # < transparently.
    body = json.dumps(payload, separators=(",", ":")).replace("<", "\\u003c")
    return (
        f'{START}\n'
        f'<script id="precomputed-data" type="application/json">{body}</script>\n'
        f'{END}'
    )


def embed(html: str, block: str) -> str:
    if START in html and END in html:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            lambda _m: block,
            html,
            count=1,
            flags=re.DOTALL,
        )
    idx = html.index(APP_SCRIPT)
    return html[: idx + 1] + block + "\n" + html[idx + 1 :]


def main() -> int:
    payload = build_payload()
    block = render_block(payload)
    html = HTML.read_text()
    HTML.write_text(embed(html, block))
    kb = len(block) / 1024
    print(
        f"Embedded {len(payload['genes'])} gene(s) + index into "
        f"{HTML.relative_to(ROOT)} ({kb:.0f} KB block)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
